import { HCP, Interaction, Product, SharedMaterial } from '../types';

export const MOCK_HCPS: HCP[] = [
  {
    id: 'hcp-1',
    name: 'Dr. Ramesh Sharma',
    specialization: 'Cardiology',
    hospital: 'Fortis Escorts Heart Institute',
    city: 'New Delhi',
    lastInteraction: '2026-07-05',
    status: 'Active',
    email: 'ramesh.sharma@fortis.com',
    phone: '+91 98100 12345',
    address: 'Okhla Road, Sukhdev Vihar, New Delhi - 110025',
    notes: 'Key opinion leader in hypertension management. Prefers morning in-person visits.',
  },
  {
    id: 'hcp-2',
    name: 'Dr. Anita Desai',
    specialization: 'Endocrinology',
    hospital: 'Apollo Hospitals',
    city: 'Mumbai',
    lastInteraction: '2026-07-02',
    status: 'Active',
    email: 'anita.desai@apollo.com',
    phone: '+91 98200 54321',
    address: 'Film City Road, East Express Highway, Mumbai - 400096',
    notes: 'Very interested in our new diabetes line. Extremely detail-oriented, requests clinical studies.',
  },
  {
    id: 'hcp-3',
    name: 'Dr. Vikram Patel',
    specialization: 'Neurology',
    hospital: 'Medanta - The Medicity',
    city: 'Gurugram',
    lastInteraction: '2026-06-28',
    status: 'Active',
    email: 'vikram.patel@medanta.org',
    phone: '+91 98111 67890',
    address: 'Sector 38, Gurugram, Haryana - 122001',
    notes: 'Researches neurodegenerative diseases. Prefers video calls due to busy schedule.',
  },
  {
    id: 'hcp-4',
    name: 'Dr. Sunita Rao',
    specialization: 'Pediatrics',
    hospital: 'Manipal Hospital',
    city: 'Bengaluru',
    lastInteraction: '2026-07-07',
    status: 'Active',
    email: 'sunita.rao@manipal.edu',
    phone: '+91 98800 23456',
    address: 'HAL Airport Road, Bengaluru - 560017',
    notes: 'Focused on pediatric immunizations and growth markers. Open to samples.',
  },
  {
    id: 'hcp-5',
    name: 'Dr. Rajesh Verma',
    specialization: 'Oncology',
    hospital: 'Tata Memorial Hospital',
    city: 'Mumbai',
    lastInteraction: '2026-06-15',
    status: 'Inactive',
    email: 'rajesh.verma@tmc.gov.in',
    phone: '+91 98222 98765',
    address: 'Dr. E Borges Road, Parel, Mumbai - 400012',
    notes: 'On sabbatical for research in Europe until late 2026.',
  },
  {
    id: 'hcp-6',
    name: 'Dr. Preeti Gupta',
    specialization: 'Dermatology',
    hospital: 'Max Super Speciality Hospital',
    city: 'New Delhi',
    lastInteraction: '2026-07-06',
    status: 'Active',
    email: 'preeti.gupta@maxhealthcare.com',
    phone: '+91 98123 45678',
    address: 'Saket, New Delhi - 110017',
    notes: 'Writes many prescriptions for topical treatments. Loves new samples.',
  },
  {
    id: 'hcp-7',
    name: 'Dr. Arjun Mehta',
    specialization: 'Orthopedics',
    hospital: 'Kokilaben Dhirubhai Ambani Hospital',
    city: 'Mumbai',
    lastInteraction: '2026-07-01',
    status: 'Pending',
    email: 'arjun.mehta@kokilaben.com',
    phone: '+91 98300 87654',
    address: 'Rao Saheb Achutrao Patwardhan Marg, Four Bungalows, Mumbai - 400053',
    notes: 'Recently joined the hospital board. Needs introductory detailing session.',
  }
];

export const MOCK_PRODUCTS: Product[] = [
  { id: 'p-1', name: 'GliclaCare XR (Diabetes)', category: 'Endocrinology' },
  { id: 'p-2', name: 'CardioSart HCT (Hypertension)', category: 'Cardiology' },
  { id: 'p-3', name: 'NeuroProtect Cit (Cognitive)', category: 'Neurology' },
  { id: 'p-4', name: 'DermaSoothe HC (Topical Steroid)', category: 'Dermatology' },
  { id: 'p-5', name: 'Pediatrix Multi-V (Nutritional)', category: 'Pediatrics' },
];

export const MOCK_MATERIALS: SharedMaterial[] = [
  { id: 'm-1', name: 'GliclaCare XR Clinical Trial Summary (Phase III)', type: 'Clinical Trial' },
  { id: 'm-2', name: 'CardioSart HCT Patient Brochure', type: 'Brochure' },
  { id: 'm-3', name: 'NeuroProtect Cit Mode of Action Slide Deck', type: 'Presentation' },
  { id: 'm-4', name: 'DermaSoothe HC Efficacy and Safety Profile', type: 'Safety Data Sheet' },
  { id: 'm-5', name: 'Pediatrix Multi-V Pediatric Dosage Guidelines', type: 'Brochure' }
];

export const MOCK_INTERACTIONS: Interaction[] = [
  {
    id: 'int-1',
    hcpId: 'hcp-1',
    hcpName: 'Dr. Ramesh Sharma',
    type: 'In-Person',
    date: '2026-07-05',
    time: '11:30',
    attendees: ['Sales Rep Amit Kumar', 'Dr. Ramesh Sharma'],
    topicsDiscussed: ['CardioSart HCT Efficacy', 'Hypertension Patient Compliance'],
    sentiment: 'Positive',
    outcome: 'Dr. Sharma was impressed by the CardioSart HCT compliance study. He plans to prescribe it to 10 new patients in the next month.',
    followUpActions: 'Send the physical brochure on CardioSart HCT to Fortis Escorts Hospital reception.',
    materialsShared: ['CardioSart HCT Patient Brochure'],
    samplesDistributed: [{ productName: 'CardioSart HCT (Hypertension)', quantity: 20 }],
    aiSuggestedFollowUps: ['Deliver brochures to reception', 'Schedule next meeting in 4 weeks']
  },
  {
    id: 'int-2',
    hcpId: 'hcp-2',
    hcpName: 'Dr. Anita Desai',
    type: 'Video Call',
    date: '2026-07-02',
    time: '15:00',
    attendees: ['Sales Rep Amit Kumar', 'Dr. Anita Desai', 'Clinic Manager Priya'],
    topicsDiscussed: ['GliclaCare XR Clinical Trial Summary (Phase III)', 'Diabetes Care Advancements'],
    sentiment: 'Neutral',
    outcome: 'Discussed clinical trial data for GliclaCare XR. Dr. Desai wants to see more data on cardiovascular safety trials before changing her standard prescriptions.',
    followUpActions: 'Email the GliclaCare Phase III cardiovascular safety study PDF.',
    materialsShared: ['GliclaCare XR Clinical Trial Summary (Phase III)'],
    samplesDistributed: [],
    aiSuggestedFollowUps: ['Email cardiovascular safety study PDF', 'Follow up via call in 2 weeks']
  },
  {
    id: 'int-3',
    hcpId: 'hcp-4',
    hcpName: 'Dr. Sunita Rao',
    type: 'In-Person',
    date: '2026-07-07',
    time: '10:00',
    attendees: ['Sales Rep Amit Kumar', 'Dr. Sunita Rao'],
    topicsDiscussed: ['Pediatrix Multi-V Pediatric Dosage Guidelines', 'Nutrition Deficiencies'],
    sentiment: 'Positive',
    outcome: 'Presented Pediatric dosage rules. Dr. Rao liked the flavor profiling and will stock the samples in her pediatric clinic dispensary.',
    followUpActions: 'Deliver 50 more samples of Pediatrix Multi-V to her clinic.',
    materialsShared: ['Pediatrix Multi-V Pediatric Dosage Guidelines'],
    samplesDistributed: [{ productName: 'Pediatrix Multi-V (Nutritional)', quantity: 15 }],
    aiSuggestedFollowUps: ['Deliver 50 more samples of Pediatrix Multi-V', 'Invite Dr. Rao to nutrition webinar']
  },
  {
    id: 'int-4',
    hcpId: 'hcp-6',
    hcpName: 'Dr. Preeti Gupta',
    type: 'Phone Call',
    date: '2026-07-06',
    time: '16:45',
    attendees: ['Sales Rep Amit Kumar', 'Dr. Preeti Gupta'],
    topicsDiscussed: ['DermaSoothe HC Efficacy and Safety Profile'],
    sentiment: 'Positive',
    outcome: 'Dr. Preeti reported that patients treated with DermaSoothe HC experienced less skin irritation. She requested a detailed safety sheet.',
    followUpActions: 'Share digital copy of Safety Data Sheet via WhatsApp/Email.',
    materialsShared: ['DermaSoothe HC Efficacy and Safety Profile'],
    samplesDistributed: [],
    aiSuggestedFollowUps: ['Share digital Safety Data Sheet', 'Confirm receipt of digital sheet']
  }
];
